import { TokenData } from '@/types/token';

// Utility function to generate random data
const randomBetween = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
const randomFloat = (min: number, max: number, decimals: number = 2) => 
  Number((Math.random() * (max - min) + min).toFixed(decimals));

// Sample token logos (placeholder gradients)
const tokenLogos = [
  '/tokens/t1.svg',
  '/tokens/t2.svg',
  '/tokens/t3.svg',
];

const tokenNames = [
  { symbol: 'TEST', name: 'test' },
  { symbol: 'JUDGE', name: 'You Be The Judge' },
  { symbol: 'TESLA AI', name: 'Tesla AI' },
  { symbol: 'COOCHI', name: 'Coochi' },
  { symbol: 'FURIEVERSE', name: 'The Furieverse' },
  { symbol: 'TLDICK', name: 'Fallos Traffic Light' },
  { symbol: 'NSF', name: 'Nick Shirley Fund' },
  { symbol: 'JupUSD', name: 'JupUSD' },
  { symbol: 'DUMB', name: 'dumb' },
  { symbol: 'INVASION', name: 'Swedes Invasion' },
  { symbol: 'TRUST', name: 'Launch Coin on Trust' },
  { symbol: 'PRODUCT', name: 'Not A Coin' },
  { symbol: 'ACT', name: 'Aaron Capitals' },
  { symbol: 'REDBULL', name: 'RedBull Official Token' },
];

const creatorNames = [
  'GuRf...pump', 'J5Hk...cJ7W', 'GhHX...yoWZ', 'HRMV...pump',
  'Hwjs...pump', 'DFAP...wnHK', 'DPJC...A8Pt', '43VM...ovKU',
  '6jnz...pump', '2XV1...', 'Brmt...PNR6',
];

const ages = ['0s', '1s', '2s', '3s', '5s', '10s', '30s', '1m', '2m', '3m', '5m', '1h', '2h', '5d'];

export function generateMockToken(index: number, column: 'new-pairs' | 'final-stretch' | 'migrated'): TokenData {
  const tokenInfo = tokenNames[index % tokenNames.length];
  const creatorName = creatorNames[index % creatorNames.length];
  
  const baseMarketCap = column === 'new-pairs' 
    ? randomBetween(3000, 50000) 
    : column === 'final-stretch' 
    ? randomBetween(4000, 400000) 
    : randomBetween(50000, 800000);
  
  const baseVolume = column === 'new-pairs' 
    ? randomBetween(500, 15000) 
    : column === 'final-stretch' 
    ? randomBetween(2000, 20000) 
    : randomBetween(10000, 200000);

  const txCount = column === 'new-pairs' 
    ? randomBetween(2, 30) 
    : column === 'final-stretch' 
    ? randomBetween(20, 2000) 
    : randomBetween(100, 3500);

  const age = column === 'new-pairs' 
    ? ages[randomBetween(0, 4)] 
    : column === 'final-stretch' 
    ? ages[randomBetween(4, 10)] 
    : ages[randomBetween(8, 13)];

  const progressPercent = column === 'final-stretch' ? randomBetween(30, 95) : undefined;

  // Generate a random Solana-like address
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789';
  const address = Array.from({ length: 44 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');

  return {
    id: `token-${column}-${index}`,
    symbol: tokenInfo.symbol,
    name: tokenInfo.name,
    logo: tokenLogos[index % tokenLogos.length],
    address,
    age,
    marketCap: baseMarketCap,
    volume: baseVolume,
    price: randomFloat(0.001, 0.1, 4),
    txCount,
    priceChange: randomFloat(-50, 100, 0),
    holders: randomBetween(0, 300),
    liquidity: randomBetween(1000, 50000),
    devSold: randomFloat(0, 100, 0),
    insiderPercent: randomFloat(0, 20, 0),
    bundlePercent: randomFloat(0, 15, 0),
    sniperPercent: randomFloat(0, 10, 0),
    top10Percent: randomFloat(5, 50, 0),
    creatorAddress: `${creatorName.slice(0, 4)}...${creatorName.slice(-4)}`,
    creatorName,
    verified: Math.random() > 0.7,
    hasAudit: Math.random() > 0.8,
    hasTelegram: Math.random() > 0.4,
    hasTwitter: Math.random() > 0.5,
    hasWebsite: Math.random() > 0.6,
    isNew: column === 'new-pairs' && index < 3,
    progressPercent,
    socialLinks: {
      telegram: Math.random() > 0.4 ? 'https://t.me/token' : undefined,
      twitter: Math.random() > 0.5 ? 'https://twitter.com/token' : undefined,
      website: Math.random() > 0.6 ? 'https://token.io' : undefined,
    },
  };
}

export function generateColumnData(column: 'new-pairs' | 'final-stretch' | 'migrated', count: number = 8): TokenData[] {
  return Array.from({ length: count }, (_, i) => generateMockToken(i, column));
}

export const mockNewPairs: TokenData[] = [
  {
    id: 'new-1',
    symbol: 'FATAL',
    name: 'fatal',
    logo: '/tokens/fatal.svg',
    age: '0s',
    marketCap: 4410,
    volume: 462,
    price: 0.027,
    txCount: 7,
    priceChange: 9,
    holders: 1,
    liquidity: 1000,
    devSold: 9,
    insiderPercent: 9,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 9,
    creatorAddress: 'C4rs...pump',
    creatorName: 'C4rs...pump',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: true,
    hasWebsite: false,
    isNew: true,
    progressPercent: 3,
  },
  {
    id: 'new-2',
    symbol: 'AMERICAN',
    name: 'Ame...',
    logo: '/tokens/american.svg',
    age: '0s',
    marketCap: 5730,
    volume: 809,
    price: 0.025,
    txCount: 3,
    priceChange: 16,
    holders: 2,
    liquidity: 1500,
    devSold: 11,
    insiderPercent: 16,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 16,
    creatorAddress: '3Ffu...JtA6',
    creatorName: '3Ffu...JtA6',
    verified: true,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
    isNew: true,
    progressPercent: 23,
  },
  {
    id: 'new-3',
    symbol: 'CHINA',
    name: 'MAD...',
    logo: '/tokens/china.svg',
    age: '4s',
    marketCap: 3520,
    volume: 6,
    price: 0.032,
    txCount: 2,
    priceChange: 0,
    holders: 1,
    liquidity: 800,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 0,
    creatorAddress: 'GfJn...pump',
    creatorName: 'GfJn...pump',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: true,
    hasWebsite: false,
    isNew: true,
    progressPercent: 1,
  },
  {
    id: 'new-4',
    symbol: 'JAX',
    name: 'RIP ...',
    logo: '/tokens/jax.svg',
    age: '5s',
    marketCap: 4110,
    volume: 377,
    price: 0.036,
    txCount: 2,
    priceChange: 5,
    holders: 1,
    liquidity: 900,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 5,
    creatorAddress: 'JxRp...mK2L',
    creatorName: 'JxRp...mK2L',
    verified: true,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: false,
    isNew: true,
    progressPercent: 2,
  },
  {
    id: 'new-5',
    symbol: 'TEST',
    name: 'test',
    logo: '/tokens/test.svg',
    age: '0s',
    marketCap: 3530,
    volume: 1000,
    price: 0.034,
    txCount: 2,
    priceChange: 0,
    holders: 0,
    liquidity: 1000,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 0,
    creatorAddress: 'GuRf...pump',
    creatorName: 'GuRf...pump',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
    isNew: true,
  },
  {
    id: 'new-6',
    symbol: 'JUDGE',
    name: 'You Be The Judge',
    logo: '/tokens/judge.svg',
    age: '2s',
    marketCap: 6400,
    volume: 1000,
    price: 0.049,
    txCount: 7,
    priceChange: 24,
    holders: 5,
    liquidity: 2000,
    devSold: 8,
    insiderPercent: 14,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 8,
    creatorAddress: 'J5Hk...cJ7W',
    creatorName: 'J5Hk...cJ7W',
    verified: true,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: false,
    hasWebsite: true,
    isNew: true,
    progressPercent: 23,
  },
  {
    id: 'new-7',
    symbol: 'TESLA AI',
    name: 'Tesla AI',
    logo: '/tokens/tesla.svg',
    age: '3s',
    marketCap: 42500,
    volume: 11000,
    price: 0.048,
    txCount: 8,
    priceChange: 74,
    holders: 6,
    liquidity: 5000,
    devSold: 74,
    insiderPercent: 74,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 74,
    creatorAddress: 'GhHX...yoWZ',
    creatorName: 'GhHX...yoWZ',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
    progressPercent: 0,
  },
  {
    id: 'new-8',
    symbol: 'COOCHI',
    name: 'Coochi',
    logo: '/tokens/coochi.svg',
    age: '5s',
    marketCap: 4840,
    volume: 2000,
    price: 0.044,
    txCount: 28,
    priceChange: 16,
    holders: 7,
    liquidity: 3000,
    devSold: 15,
    insiderPercent: 15,
    bundlePercent: 0,
    sniperPercent: 15,
    top10Percent: 16,
    creatorAddress: 'HRMV...pump',
    creatorName: 'HRMV...pump',
    verified: false,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: false,
    hasWebsite: false,
    progressPercent: 8,
  },
  {
    id: 'new-9',
    symbol: 'FURIEVERSE',
    name: 'The Furieverse',
    logo: '/tokens/furie.svg',
    age: '10s',
    marketCap: 3950,
    volume: 570,
    price: 0.041,
    txCount: 5,
    priceChange: -5,
    holders: 3,
    liquidity: 1500,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 12,
    creatorAddress: 'XmNp...kL2Q',
    creatorName: 'XmNp...kL2Q',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
  },
];

export const mockFinalStretch: TokenData[] = [
  {
    id: 'final-1',
    symbol: 'TLDICK',
    name: 'Fallos Traffic Light',
    logo: '/tokens/tldick.svg',
    age: '5d',
    marketCap: 4370,
    volume: 2000,
    price: 0.077,
    txCount: 134,
    priceChange: 89,
    holders: 10,
    liquidity: 3000,
    devSold: 1,
    insiderPercent: 16,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 89,
    creatorAddress: 'Hwjs...pump',
    creatorName: 'Hwjs...pump',
    verified: false,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: false,
    progressPercent: 89,
  },
  {
    id: 'final-2',
    symbol: 'NSF',
    name: 'Nick Shirley Fund',
    logo: '/tokens/nsf.svg',
    age: '1h',
    marketCap: 30600,
    volume: 13000,
    price: 0.011,
    txCount: 1992,
    priceChange: 31,
    holders: 203,
    liquidity: 8000,
    devSold: 23,
    insiderPercent: 46,
    bundlePercent: 50,
    sniperPercent: 0,
    top10Percent: 31,
    creatorAddress: 'DFAP...wnHK',
    creatorName: 'DFAP...wnHK',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
    progressPercent: 31,
  },
  {
    id: 'final-3',
    symbol: 'JupUSD',
    name: 'JupUSD',
    logo: '/tokens/jupusd.svg',
    age: '1m',
    marketCap: 354000,
    volume: 16000,
    price: 0.033,
    txCount: 40,
    priceChange: 95,
    holders: 28,
    liquidity: 15000,
    devSold: 0,
    insiderPercent: 95,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 95,
    creatorAddress: 'DPJC...A8Pt',
    creatorName: 'DPJC...A8Pt',
    verified: true,
    hasAudit: true,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: true,
    progressPercent: 95,
  },
  {
    id: 'final-4',
    symbol: 'TESLA AI',
    name: 'Tesla AI',
    logo: '/tokens/tesla2.svg',
    age: '3s',
    marketCap: 42500,
    volume: 11000,
    price: 0.048,
    txCount: 8,
    priceChange: 74,
    holders: 6,
    liquidity: 5000,
    devSold: 74,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 74,
    creatorAddress: 'GhHX...yoWZ',
    creatorName: 'GhHX...yoWZ',
    verified: false,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: false,
    hasWebsite: false,
    progressPercent: 74,
  },
  {
    id: 'final-5',
    symbol: 'REDBULL',
    name: 'RedBull Official Token',
    logo: '/tokens/redbull.svg',
    age: '2h',
    marketCap: 12600,
    volume: 8000,
    price: 0.025,
    txCount: 89,
    priceChange: 45,
    holders: 42,
    liquidity: 4500,
    devSold: 10,
    insiderPercent: 22,
    bundlePercent: 5,
    sniperPercent: 3,
    top10Percent: 38,
    creatorAddress: 'RbTk...oP3X',
    creatorName: 'RbTk...oP3X',
    verified: true,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: true,
    progressPercent: 65,
  },
];

export const mockMigrated: TokenData[] = [
  {
    id: 'migrated-1',
    symbol: 'DUMB',
    name: 'dumb',
    logo: '/tokens/dumb.svg',
    age: '1m',
    marketCap: 549000,
    volume: 16000,
    price: 0.0022,
    txCount: 342,
    priceChange: 97,
    holders: 163,
    liquidity: 25000,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 0,
    sniperPercent: 0,
    top10Percent: 97,
    creatorAddress: '43VM...ovKU',
    creatorName: '43VM...ovKU',
    verified: true,
    hasAudit: false,
    hasTelegram: false,
    hasTwitter: true,
    hasWebsite: false,
  },
  {
    id: 'migrated-2',
    symbol: 'INVASION',
    name: 'Swedes Invasion',
    logo: '/tokens/invasion.svg',
    age: '1m',
    marketCap: 64400,
    volume: 174000,
    price: 12.59,
    txCount: 3022,
    priceChange: 18,
    holders: 410,
    liquidity: 35000,
    devSold: 0,
    insiderPercent: 0,
    bundlePercent: 3,
    sniperPercent: 2,
    top10Percent: 18,
    creatorAddress: '6jnz...pump',
    creatorName: '6jnz...pump',
    verified: true,
    hasAudit: true,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: true,
    progressPercent: 100,
  },
  {
    id: 'migrated-3',
    symbol: 'TRUST',
    name: 'Launch Coin on Trust',
    logo: '/tokens/trust.svg',
    age: '1m',
    marketCap: 52000,
    volume: 13000,
    price: 0.022,
    txCount: 184,
    priceChange: 2,
    holders: 180,
    liquidity: 12000,
    devSold: 79,
    insiderPercent: 8,
    bundlePercent: 8,
    sniperPercent: 0,
    top10Percent: 2,
    creatorAddress: '2XV1...',
    creatorName: '2XV1...',
    verified: false,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: true,
    progressPercent: 100,
  },
  {
    id: 'migrated-4',
    symbol: 'PRODUCT',
    name: 'Not A Coin',
    logo: '/tokens/product.svg',
    age: '2m',
    marketCap: 752000,
    volume: 19000,
    price: 0.024,
    txCount: 297,
    priceChange: 100,
    holders: 3,
    liquidity: 45000,
    devSold: 19,
    insiderPercent: 19,
    bundlePercent: 0,
    sniperPercent: 19,
    top10Percent: 100,
    creatorAddress: 'Brmt...PNR6',
    creatorName: 'Brmt...PNR6',
    verified: true,
    hasAudit: true,
    hasTelegram: true,
    hasTwitter: false,
    hasWebsite: true,
    progressPercent: 100,
  },
  {
    id: 'migrated-5',
    symbol: 'ACT',
    name: 'Aaron Capitals',
    logo: '/tokens/act.svg',
    age: '5m',
    marketCap: 63100,
    volume: 21000,
    price: 0.019,
    txCount: 456,
    priceChange: 35,
    holders: 89,
    liquidity: 18000,
    devSold: 5,
    insiderPercent: 12,
    bundlePercent: 2,
    sniperPercent: 1,
    top10Percent: 28,
    creatorAddress: 'AcTk...Cp4L',
    creatorName: 'AcTk...Cp4L',
    verified: true,
    hasAudit: false,
    hasTelegram: true,
    hasTwitter: true,
    hasWebsite: true,
    progressPercent: 100,
  },
];

