import { NextResponse } from 'next/server';

// Axiom API endpoint (this may need adjustment based on their actual API)
const AXIOM_API_BASE = 'https://axiom.trade';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const column = searchParams.get('column') || 'new-pairs';
  const chain = searchParams.get('chain') || 'sol';

  try {
    // Try to fetch from Axiom's API
    // Note: The actual API endpoint structure may vary
    const response = await fetch(`${AXIOM_API_BASE}/api/pulse?chain=${chain}&type=${column}`, {
      headers: {
        'Accept': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      },
      next: { revalidate: 5 }, // Cache for 5 seconds
    });

    if (!response.ok) {
      // If API fails, return mock data with simulated real-time changes
      return NextResponse.json(generateMockRealTimeData(column));
    }

    const data = await response.json();
    return NextResponse.json(data);
  } catch (error) {
    // Fallback to mock data with simulated price changes
    console.log('Using mock data due to API error:', error);
    return NextResponse.json(generateMockRealTimeData(column));
  }
}

// Generate mock data with simulated real-time price changes
function generateMockRealTimeData(column: string) {
  const baseTokens = getBaseTokens(column);
  
  // Add random price fluctuations to simulate real-time data
  return baseTokens.map(token => ({
    ...token,
    price: token.price * (1 + (Math.random() - 0.5) * 0.1), // ±5% fluctuation
    priceChange: token.priceChange + (Math.random() - 0.5) * 10,
    volume: token.volume * (1 + (Math.random() - 0.5) * 0.2),
    txCount: token.txCount + Math.floor(Math.random() * 5),
    lastUpdate: Date.now(),
  }));
}

function getBaseTokens(column: string) {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789';
  const generateAddress = () => Array.from({ length: 44 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');

  if (column === 'new-pairs') {
    return [
      {
        id: 'realtime-1',
        symbol: 'FATAL',
        name: 'fatal',
        address: generateAddress(),
        age: '0s',
        marketCap: 4410 + Math.random() * 500,
        volume: 462 + Math.random() * 100,
        price: 0.027 + Math.random() * 0.005,
        txCount: 7 + Math.floor(Math.random() * 3),
        priceChange: 9 + (Math.random() - 0.5) * 5,
        holders: 1 + Math.floor(Math.random() * 2),
        liquidity: 1000,
        devSold: 9,
        insiderPercent: 9,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 9,
        creatorAddress: 'C4rs...pump',
        creatorName: 'C4rs...pump',
        verified: false,
        hasAudit: false,
        hasTelegram: false,
        hasTwitter: true,
        hasWebsite: false,
        isNew: true,
        progressPercent: 3,
      },
      {
        id: 'realtime-2',
        symbol: 'AMERICAN',
        name: 'AmeriCan',
        address: generateAddress(),
        age: '0s',
        marketCap: 5730 + Math.random() * 800,
        volume: 809 + Math.random() * 200,
        price: 0.025 + Math.random() * 0.008,
        txCount: 3 + Math.floor(Math.random() * 5),
        priceChange: 16 + (Math.random() - 0.5) * 8,
        holders: 2 + Math.floor(Math.random() * 3),
        liquidity: 1500,
        devSold: 11,
        insiderPercent: 16,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 16,
        creatorAddress: '3Ffu...JtA6',
        creatorName: '3Ffu...JtA6',
        verified: true,
        hasAudit: false,
        hasTelegram: false,
        hasTwitter: false,
        hasWebsite: false,
        isNew: true,
        progressPercent: 23,
      },
      {
        id: 'realtime-3',
        symbol: 'CHINA',
        name: 'MAD CHINA',
        address: generateAddress(),
        age: '4s',
        marketCap: 3520 + Math.random() * 400,
        volume: 6 + Math.random() * 10,
        price: 0.032 + Math.random() * 0.003,
        txCount: 2 + Math.floor(Math.random() * 2),
        priceChange: (Math.random() - 0.5) * 10,
        holders: 1,
        liquidity: 800,
        devSold: 0,
        insiderPercent: 0,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 0,
        creatorAddress: 'GfJn...pump',
        creatorName: 'GfJn...pump',
        verified: false,
        hasAudit: false,
        hasTelegram: false,
        hasTwitter: true,
        hasWebsite: false,
        isNew: true,
        progressPercent: 1,
      },
      {
        id: 'realtime-4',
        symbol: 'JAX',
        name: 'RIP JAX',
        address: generateAddress(),
        age: '5s',
        marketCap: 4110 + Math.random() * 300,
        volume: 377 + Math.random() * 50,
        price: 0.036 + Math.random() * 0.004,
        txCount: 2 + Math.floor(Math.random() * 3),
        priceChange: 5 + (Math.random() - 0.5) * 4,
        holders: 1,
        liquidity: 900,
        devSold: 0,
        insiderPercent: 0,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 5,
        creatorAddress: 'JxRp...mK2L',
        creatorName: 'JxRp...mK2L',
        verified: true,
        hasAudit: false,
        hasTelegram: true,
        hasTwitter: true,
        hasWebsite: false,
        isNew: true,
        progressPercent: 2,
      },
      {
        id: 'realtime-5',
        symbol: 'MOON',
        name: 'To The Moon',
        address: generateAddress(),
        age: '2s',
        marketCap: 6200 + Math.random() * 1000,
        volume: 1200 + Math.random() * 300,
        price: 0.045 + Math.random() * 0.01,
        txCount: 12 + Math.floor(Math.random() * 8),
        priceChange: 25 + (Math.random() - 0.5) * 15,
        holders: 5 + Math.floor(Math.random() * 3),
        liquidity: 2000,
        devSold: 5,
        insiderPercent: 12,
        bundlePercent: 2,
        sniperPercent: 1,
        top10Percent: 18,
        creatorAddress: 'MnPk...x92Q',
        creatorName: 'MnPk...x92Q',
        verified: true,
        hasAudit: false,
        hasTelegram: true,
        hasTwitter: true,
        hasWebsite: true,
        isNew: true,
        progressPercent: 8,
      },
    ];
  }

  if (column === 'final-stretch') {
    return [
      {
        id: 'fs-1',
        symbol: 'TLDICK',
        name: 'Traffic Light',
        address: generateAddress(),
        age: '5d',
        marketCap: 4370 + Math.random() * 500,
        volume: 2000 + Math.random() * 400,
        price: 0.077 + Math.random() * 0.01,
        txCount: 134 + Math.floor(Math.random() * 20),
        priceChange: 89 + (Math.random() - 0.5) * 10,
        holders: 10 + Math.floor(Math.random() * 5),
        liquidity: 3000,
        devSold: 1,
        insiderPercent: 16,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 89,
        creatorAddress: 'Hwjs...pump',
        creatorName: 'Hwjs...pump',
        verified: false,
        hasAudit: false,
        hasTelegram: true,
        hasTwitter: true,
        hasWebsite: false,
        isNew: false,
        progressPercent: 89,
      },
      {
        id: 'fs-2',
        symbol: 'NSF',
        name: 'Nick Shirley Fund',
        address: generateAddress(),
        age: '1h',
        marketCap: 30600 + Math.random() * 2000,
        volume: 13000 + Math.random() * 1500,
        price: 0.011 + Math.random() * 0.002,
        txCount: 1992 + Math.floor(Math.random() * 50),
        priceChange: 31 + (Math.random() - 0.5) * 8,
        holders: 203 + Math.floor(Math.random() * 10),
        liquidity: 8000,
        devSold: 23,
        insiderPercent: 46,
        bundlePercent: 50,
        sniperPercent: 0,
        top10Percent: 31,
        creatorAddress: 'DFAP...wnHK',
        creatorName: 'DFAP...wnHK',
        verified: false,
        hasAudit: false,
        hasTelegram: false,
        hasTwitter: false,
        hasWebsite: false,
        isNew: false,
        progressPercent: 31,
      },
      {
        id: 'fs-3',
        symbol: 'JupUSD',
        name: 'JupUSD',
        address: generateAddress(),
        age: '1m',
        marketCap: 354000 + Math.random() * 10000,
        volume: 16000 + Math.random() * 2000,
        price: 0.033 + Math.random() * 0.005,
        txCount: 40 + Math.floor(Math.random() * 10),
        priceChange: 95 + (Math.random() - 0.5) * 5,
        holders: 28 + Math.floor(Math.random() * 5),
        liquidity: 15000,
        devSold: 0,
        insiderPercent: 95,
        bundlePercent: 0,
        sniperPercent: 0,
        top10Percent: 95,
        creatorAddress: 'DPJC...A8Pt',
        creatorName: 'DPJC...A8Pt',
        verified: true,
        hasAudit: true,
        hasTelegram: true,
        hasTwitter: true,
        hasWebsite: true,
        isNew: false,
        progressPercent: 95,
      },
    ];
  }

  // Migrated tokens
  return [
    {
      id: 'mig-1',
      symbol: 'DUMB',
      name: 'dumb',
      address: generateAddress(),
      age: '1m',
      marketCap: 549000 + Math.random() * 20000,
      volume: 16000 + Math.random() * 3000,
      price: 0.0022 + Math.random() * 0.0005,
      txCount: 342 + Math.floor(Math.random() * 30),
      priceChange: 97 + (Math.random() - 0.5) * 5,
      holders: 163 + Math.floor(Math.random() * 10),
      liquidity: 25000,
      devSold: 0,
      insiderPercent: 0,
      bundlePercent: 0,
      sniperPercent: 0,
      top10Percent: 97,
      creatorAddress: '43VM...ovKU',
      creatorName: '43VM...ovKU',
      verified: true,
      hasAudit: false,
      hasTelegram: false,
      hasTwitter: true,
      hasWebsite: false,
      isNew: false,
      progressPercent: 100,
    },
    {
      id: 'mig-2',
      symbol: 'INVASION',
      name: 'Swedes Invasion',
      address: generateAddress(),
      age: '1m',
      marketCap: 64400 + Math.random() * 5000,
      volume: 174000 + Math.random() * 10000,
      price: 12.59 + Math.random() * 0.5,
      txCount: 3022 + Math.floor(Math.random() * 100),
      priceChange: 18 + (Math.random() - 0.5) * 8,
      holders: 410 + Math.floor(Math.random() * 20),
      liquidity: 35000,
      devSold: 0,
      insiderPercent: 0,
      bundlePercent: 3,
      sniperPercent: 2,
      top10Percent: 18,
      creatorAddress: '6jnz...pump',
      creatorName: '6jnz...pump',
      verified: true,
      hasAudit: true,
      hasTelegram: true,
      hasTwitter: true,
      hasWebsite: true,
      isNew: false,
      progressPercent: 100,
    },
    {
      id: 'mig-3',
      symbol: 'TRUST',
      name: 'Launch Coin',
      address: generateAddress(),
      age: '1m',
      marketCap: 52000 + Math.random() * 3000,
      volume: 13000 + Math.random() * 1500,
      price: 0.022 + Math.random() * 0.003,
      txCount: 184 + Math.floor(Math.random() * 15),
      priceChange: 2 + (Math.random() - 0.5) * 10,
      holders: 180 + Math.floor(Math.random() * 8),
      liquidity: 12000,
      devSold: 79,
      insiderPercent: 8,
      bundlePercent: 8,
      sniperPercent: 0,
      top10Percent: 2,
      creatorAddress: '2XV1...',
      creatorName: '2XV1...',
      verified: false,
      hasAudit: false,
      hasTelegram: true,
      hasTwitter: true,
      hasWebsite: true,
      isNew: false,
      progressPercent: 100,
    },
  ];
}

